import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';
import 'package:sqflite/sqlite_api.dart';

class SQLDatabase {
  SQLDatabase();

  List results;
  bool start = false;

  SQLDatabase._();

  static final SQLDatabase db = SQLDatabase._();
  static Database _database;

  Future<Database> get database async {
    if (_database != null) return _database;
    _database = await initDB();
    return _database;
  }

  initDB() async {
    String path = join(await getDatabasesPath(), 'movie.db');
    return await openDatabase(path, version: 5, onOpen: (db) {},
        onCreate: (Database db, int version) async {
      await db.execute(
        "CREATE TABLE movies(id INTEGER PRIMARY KEY AUTOINCREMENT , movieId TEXT, movieImgPoster TEXT, movieRate TEXT, movieDate TEXT, movieImgCover TEXT, movieOverview TEXT)",
      );
    });
  }

  Future<num> getAllMovies(String id) async {
    final db = await database;
    var data = await db.query("movies");
    print("...............................");
    print(data);
    print("...............................");
    // var result = await db.rawQuery('SELECT COUNT(*) FROM movies WHERE movieId = $id ' );//.query("movies",);
    num result = Sqflite.firstIntValue(
        await db.rawQuery('SELECT COUNT(*) FROM movies WHERE movieId = $id '));
    return result; //.toList();
  }

  getAllMovies2() async {
    final db = await database;
    var data = await db.rawQuery('SELECT movieId FROM movies  ');
    print("...............................");
    print(data);
    print("...............................");
    return data.toList();
  }

  insert(String movieId, String movieImgPoster, String movieRate,
      String movieDate, String movieImgCover, String movieOverview) async {
    final db = await database;
    var result;
    print("vvvvvvvvvvvvvvvvvvvvvvvvvvv");
    try {
      result = await db.rawInsert(
          "INSERT Into movies ( movieId, movieImgPoster , movieRate , movieDate , movieImgCover , movieOverview )"
          " VALUES ( ?,?,?,?,?,?)",
          [
            movieId,
            movieImgPoster,
            movieRate,
            movieDate,
            movieImgCover,
            movieOverview
          ]);
    } catch (e) {
      print("eeeeeeeeeeee$e");
    }

    return result;
  }

  Future<void> delete(String id) async {
    final db = await database;
    await db.delete(
      'movies',
      where: "movieId = ?",
      whereArgs: [id],
    );
  }
}

class Autogenerated {
  int movieId;

  Autogenerated({this.movieId});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    movieId = json['movieId'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['movieId'] = this.movieId;
    return data;
  }
}
